### ISSUE TITLE
How to extend free space to install more module??

### ISSUE THREAD

**Issue by tirajetw** [SecurityAddicted/pineapple-ar150#1]
Hello , I can not install module. 
It say
**"You do not have enough free space to install this module. Please insert an SD card and ensure that it is formatted correctly."**
How to extend free space to install more module??

sorry for my bad english, Thank you

**Comment by SecurityAddicted** [comment]
Unfortunately the space available is limited on the AR150. The Pineapple Nano has and SD slot so you can install many more modules on it.
So no fix for this I'm sorry, except if you find a way to add the SD slot :)
