### ISSUE TITLE
New pineapple firmware imminent!

### ISSUE THREAD

**Issue by bruvv** [SecurityAddicted/pineapple-ar150#12]
@SecurityAddicted are you still going to create a new firmware when it gets released? They're almost ready to deploy the new firmware. 
https://forums.hak5.org/topic/43163-wifi-pineapple-recon-bug/?do=findComment&comment=306356

**Comment by SecurityAddicted** [comment]
Will give a look when the new version will be available. Will do my best but do not expect it to come shortly after the official firmware.

**Comment by bruvv** [comment]
The beta is here :) 
https://forums.hak5.org/topic/43535-rc-release-wifi-pineapple-firmware-v210-rc1/
