### ISSUE TITLE
Is it possible to use internal wireless to recon and make Rouge AP

### ISSUE THREAD

**Issue by marioman68** [SecurityAddicted/pineapple-ar150#14]
is it possible to do this.  i tried scanning in recon and it will go to 100% and do nothing,  and in the WiFi client mode box no interfaces show up.  i have ways to actually connect to the internet through WiFi so the internal would be amazing to use.  Thank you for any information.

**Comment by bruvv** [comment]
https://github.com/SecurityAddicted/pineapple-ar150/issues/4

**Comment by SecurityAddicted** [comment]
Unfortunately the Pineapple firmware requires 2 wifi adapters to work correctly. As this is just a port of that firmware to the AR150, no features outside of the ones already available into the Pineapple will be implemented.
Sorry about that.
