### ISSUE TITLE
fdisk missing

### ISSUE THREAD

**Issue by bruvv** [SecurityAddicted/pineapple-ar150#15]
In the original pineapple fdisk is included but not in yours:
```
fdisk -l
fdisk: applet not found
```
Can you include it in the next version?

**Comment by SecurityAddicted** [comment]
Will add it into the next revision. Thanks.

**Comment by bruvv** [comment]
New version :)
https://forums.hak5.org/topic/43698-release-wifi-pineapple-firmware-v210/
