### ISSUE TITLE
Scan will not find home AP

### ISSUE THREAD

**Issue by RemakingEden** [SecurityAddicted/pineapple-ar150#16]
Hi, thanks for putting the updated firmware up OP!

I can't seem to get any scan results. My home network is very close by. I am using a GL150M.

Sorry if it's something obvious, i'm a bit of noob.

Thanks

**Comment by RemakingEden** [comment]
Ah I have it working with an external wifi dongle connected. Is this the only way of making it work?

**Comment by bruvv** [comment]
Yes you need 2 wifi cards in total.

**Comment by SecurityAddicted** [comment]
An external USB Wi-Fi adapter is needed for this firmware to work correctly.
