### ISSUE TITLE
May it be possible to add alfa driver

### ISSUE THREAD

**Issue by pinaplle** [SecurityAddicted/pineapple-ar150#2]
Is it possbile to get a .bin with alfa driver?
If i want to connect to a network the alfa switches off :(

**Comment by SecurityAddicted** [comment]
I'm pretty sure I included the most common wifi drivers.

I guess your issues depends on the AR150 not having enough juice to
power the Alfa.

Try connecting the Alfa to both the AR150 and an external power source
(like a power bank).

**Comment by pinaplle** [comment]
Oh ok will try it with a powerd hub
