### ISSUE TITLE
There was an error starting Recon. Please try again.

### ISSUE THREAD

**Issue by TropicMike** [SecurityAddicted/pineapple-ar150#4]
Hi - first, thanks for building this and putting it out there for us all!

I just got a brand new AR150 from Amazon a couple days ago.  I installed the pineapple 1.1.3 on top of the 1.261 (the latest) firmware using the uBoot UI.

The pineapple setup starts and I'm able to successfully set it up and see the UI/etc.  However, in Recon, if I click 'scan' I only get "There was an error starting Recon. Please try again."

There seems to be relatively few people having this issue, but it is out there.  Logs don't seem to show much and iwlist (IIRC) does show the local scanned APs from the cmdline, so it appears the radio is working.

Is anyone else getting this error on Recon using the AR150?  Is the software detecting that it's not 'official' hardware or something like that?

**Comment by SecurityAddicted** [comment]
Are you using a WiFi adapter plugged to the USB port? That's essential to reproduce the Pineapple hardware.

**Comment by TropicMike** [comment]
Ahh, no, I am not.  I missed that key piece of info!  I'll give it a shot.  Thanks!

**Comment by TropicMike** [comment]
Adding the second adapter worked - thank you!
