### ISSUE TITLE
DeAuth actions have no effect

### ISSUE THREAD

**Issue by careyer** [SecurityAddicted/pineapple-ar150#5]
Hi Alex,

first of all thank you very much for the excellent work and documentation. This is really awesome. I have just flashed my GL-AR150 with your bin and everything works just fine... ALMOST ;-)
(btw: for the 2nd WiFi adapter I use the well proven TP-Link 722N).

What's the issue then?
I noticed that all of the build in DeAuth actions (PinaAP based: e.g. ReCon View --> DeAuth complete network /or single client) as well as the DeAuth module show no effect at all. Even though it says: "Action successfully committed" all clients stay associated with their APs rock solid. It also does not make any difference which Multiplication (1..10) is used.
I tried on various networks - also in a test lab. It's almost like no DeAuth packets are being sent at all.

Can you verify this with your equipment?
I am a bit helpless what to test any further :-/

P.S: Same problem persists with the USB storage added version from serxo (based on your description)
https://github.com/serxo/ar150-wifi_pineapple/issues/3

**Comment by greenoid** [comment]
Some problem here. I use a new TP-WN722N WLAN adapter on a GL inet AR-150 with your firmware.
Now under network there are two WLAN devices: wlan0 and wlan0-1.
Question: Is wlan0-1 an alias of wlan0, that is the internal ethernet adapter? Or ist it the external TP-WN722N? Should the TP-WN722N appear as wlan1 (which is non present)?

**Comment by greenoid** [comment]
Found under
https://www.gl-inet.com/forums/topic/wifi-pineapple-nano-v1-0-6-firmware/
The Recon and PineAP scripts are hard-coeded vor device wlan1.
I only have wlan0 and wlan0-1.
I have to find out how to activate wlan1 for the TP-WN722N on USB.

**Comment by careyer** [comment]
@greenoid : That might very well be the reason for things not working properly. I also use a TP-WN7222N as external secondary Wifi Interface and I also only have wlan0 and wlan0-1. Please keep me updated if you find a solution to the problem. That would be awesome... I will also do some research on this matter.

**Comment by greenoid** [comment]
As soon as I have time I wil try to insert the kernel modul for the TP-WN722N manually per insmod, and if this does not work I will try the 1.0.6 Version of the firmware.

**Comment by greenoid** [comment]
Solution:
There is a newer generation of the TP-WN722N WLAN USB adapter Version 2.
Version 1 used Atheros hardware.
Version 2 uses Realtek hardware:

  idVendor           0x2357 
  idProduct          0x010c 
  bcdDevice            0.00
  iManufacturer           1 Realtek
  iProduct                2 802.11n NIC

According to
https://wikidevi.com/wiki/TP-LINK_TL-WN722N_v2
the driver module should be rtl8188eu
from
https://github.com/lwfinger/rtl8188eu
but there is no driver with this name in the pineapple-ar150 firmware.

If I plug in my OpenSUSE notebook, it is recognized as follows:

[285442.120091] usb 8-1: new high-speed USB device number 27 using ehci-pci
[285442.257235] usb 8-1: New USB device found, idVendor=2357, idProduct=010c
[285442.257242] usb 8-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[285442.257246] usb 8-1: Product: 802.11n NIC
[285442.257250] usb 8-1: Manufacturer: Realtek
[285442.257254] usb 8-1: SerialNumber: 00E04C0001
[285443.314778] r8188eu: module is from the staging directory, the quality is unknown, you have been warned.
[285443.316732] Chip Version Info: CHIP_8188E_Normal_Chip_TSMC_D_CUT_1T1R_RomVer(0)
[285443.348760] usbcore: registered new interface driver r8188eu

The warning is there because the hardware and the driver seem to be relatively new.

Oh my.
The README.MD should warn to not buy any TP-WN722N because you will get the incompatible v2.

**Comment by careyer** [comment]
I think this is not the final solution...
Yes there are two Hardware revisions of the 722N (v1.1 = Atheros, v2 = Realtek). 
When plugging in a 722N v1.1to the AL150 indeed a wlan1 interfaces shows up. Nevertheless the problem I described in my first post persists. Deauthing does not work at all, PineAP and Recon work very ver y unreliably (it almost seems like they counteract/block each other) and some features seem not to work. :-(

**Comment by greenoid** [comment]
Thank you for your warning. I was about to buy a Atheros based WLAN adapter instead. What WLAN chip does the original Pineapple firmware use and expect. I guess this should work the best?
There are 2 other realtek kernel modules compiled in this clone firmware. Do they work better?
(from my memory a rtl8170 one and another one which uses a firmware blob).

**Comment by careyer** [comment]
according to the spec-sheet of the wifipineapple nano it uses:

> Wireless: Atheros AR9331 + Atheros AR9271, both IEEE 802.11 b/g/n

The TP-Link 722N v1.1 uses a Atheros AR9271. - I also tried with a ALFA Network AWUS036NHA (also same chipset but higher output power). It has the same Issues. You can find a more detailed description of my findings also here: https://github.com/serxo/ar150-wifi_pineapple/issues/3#issuecomment-334584711 (cross GitHub Repo Link)

**Comment by SecurityAddicted** [comment]
Thanks for the effort in reporting those problems. I just added to the repo a new Pineapple firmware for the AR150 I built using the latest 2.0.2 version. I added a lot of WiFi drivers as well. However I didn't have time to test it. If you'll try it just let me know if it's working please :)

**Comment by SecurityAddicted** [comment]
About the issue with the new TP-Link revision of the 722, when I wrote the blog post there was only one version I was aware of, the one with the Atheros chipset. As for adding support for the new revision, that's pointless as it doesn't support monitor mode or packet injection, so it's pretty useless for a Pineapple build.

**Comment by careyer** [comment]
@SecurityAddicted : AWESOME! Will test it within the next few days. Have you been able to implement USB-Mass Storage/SD-Card support as well such as in @serxo 's version? https://github.com/serxo/ar150-wifi_pineapple

It is rather a crucial feature in order to be able to load additional modules from the Wifpinable.com Site that do not fit into the internal memory of the AL150 otherwise. This would be the perfect firmware then.

Thank you very much!

**Comment by SecurityAddicted** [comment]
I added needed modules but it needs testing. Let me know how it goes.

**Comment by SecurityAddicted** [comment]
Just updated the 2.0.2 image, added RTL8188EU firmware and fixed the problem with the getDevice() function in the GUI. Tested and working.

**Comment by careyer** [comment]
@SecurityAddicted : Hi Alex... I tried the new 2.0.2 image you provided.... It flashes and boots up okay... however when starting a Scan with Recon it shows the progress 0-100% and stopps at 100% without displaying any results. It just stops at 100%

It also boots up only once. Booting up the 2nd time the Ethernet/Management interface (WAN port) doesn't come up anymore. That happens also regardless if the 1st Time Setup Wizard was exacuted or the devices gets power cycled before using the wizard. I.e. the ethernet port only works on the first boot.

**Comment by greenoid** [comment]
Hi Alex,

I just tried your new image. It boots ok into Version 2.0.2. But: There is no wlan1 device, no WLAN Client in the dropdown menu and the TP WN722N is only recognized as another new USB device (via dmesg), nothing in the log that hints to a 2nd ethernet device at all.

In the /lib/modules/4.4.93/ directory there is no rtl8188eu module. Only rtl8187, which is the nearest. So I guess it's just the case of a missing kernel module for my TP WN722N v2 (as before).
The 100% display is just show. Nothing really happens there.

But nevertheless many thanks for providing a newer image.

**Comment by SecurityAddicted** [comment]
After some tests the 722 v2 is not going to work because it doesn't support monitor mode.
Updated the 2.0.2 image, there was problems with busybox not working correctly, now it's fixed and Recon works fine.

**Comment by careyer** [comment]
@SecurityAddicted Great! Will try the new firmware in the after-work hours today. Does the busybox fix also address the problem that the ethernet interface doesn't become active on the 2nd boot?

BTW: TP-Link 722N v1.1 worked fine in the last image! It gets mapped to wlan1 successfully. Also my 32GB USB Stick (sda1) was recognized according to the Advanced-Tap. However it was not mapped as a replacement for the SD card. I suppose one needs to edit the fstab content somehow so that sda1 gets mapped to the sd-card folder?

**Comment by careyer** [comment]
@SecurityAddicted : I tried the latest version. ReCon indeed works fine now! However the problem persists that the Management interface (Ethernet Port) does not come up on the 2nd boot (no Ping possible to 172.16.42.1). Also the Management-AP can not be connected (SSID shows but it wont connect). I.e. the device only works directly after flashing and initial configuration... Once power cycled or rebooted this problem appears.

**Comment by careyer** [comment]
@SecurityAddicted : Here we go! ;-) I figured out what the problem is: The ethernet interface (WAN Port on the AL150) comes up with the IP 192.168.1.1 after the first reboot. It should be 172.16.42.1 though. Can this be fixed somehow?

**Comment by careyer** [comment]
@SecurityAddicted : Sorry do bug you again! :-) I have spent some more days trying the latest image. Is there any possibility to fix the wrong IP address issue? Can you reconstruct that issue?
I have tried to rule out any external influences. i.e: I connect AP150 and my PC via a direct Ethernet cross-link cable (so no router/switch is involved). The PC does NOT run a DHCP server.

So here is what I do:
a.) configure static IP for PC ethernet: 192.168.1.2
b.) flash your firmware to the AL150 via its Fimrware Flash GUI at 192.168.1.1
c.) AL150 reboots after successfull firmware flash. Its ethnet interface comes up as 172.16.42.1
d.) reconfigure static IP for PC ethernet: 172.16.42.42
e.) connect WifiPinapple at 172.16.42.1:1471 and perform first time setup wizrd (works just fine)
f.) reboot WifiPinapple ... **its ethernet interface will now come up as 192.168.1.1 instead of 172.16.42.1 as before on its first boot after flashing**

After reconfiguring the PC back to a 192.168.1.x address one can still connect to the WiFi-Pinapple GUI. However most module and plugins expect the Gateway to be in the 172.16.42.x network.

Hope that helped!
Happy to hear from you!
Thomas

**Comment by eprompc** [comment]
Hello! 
I have 1.1.3 version installed. How can I update to 2.0.2??? All is working for now??

Thanks

**Comment by eprompc** [comment]
Ok, I installed firm 2.0.2,ethernet interface will now come up as 192.168.1.1 instead of 172.16.42.1. I connect to 192.168.1.1:1471 and go, but I can't install modules, get a red flashing led. What can I do???
Thanks

**Comment by greenoid** [comment]
I installed the 2.0.2 image and bought an TP Link TL-WN721N with an Atheros AR9271 Rev:1 chip. It was so far successful as it was recognized as an USB WLAN Adapter and in the GUI it appeared as client 'WLAN1'. So there are wlan0, wlan0-1 and wlan1 devices.
But recon does not show any SSID at all. It could be due to the fact that the WN721N has no external antenna, only an internal one which of course is very weak.

My question: Are there reports with an WN722N v1 (AR6971) where the Recon menu item works and produces SSIDs?
Is it therefore the way to go and buy a ALFA Networks AWUS036NHA?

**Comment by SecurityAddicted** [comment]
The 721 and 722v1 have the same wireless chip as far as I know (ar9271). The Alfa AWUS036NHA also shares the same chip but it's more powerful.

**Comment by SecurityAddicted** [comment]
Fixed version uploaded. All the problems known so far should have been sorted. Try it and let me know.

**Comment by careyer** [comment]
Yeah! This issue has been sorted out! DeAuth from ReCon Tab works now like a charm!
