### ISSUE TITLE
Downloading Modules

### ISSUE THREAD

**Issue by l0ndon** [SecurityAddicted/pineapple-ar150#6]
Thank you, i just upgraded to 2.0.2.
But I just have a problem when trying to install modules on the GUI.
When clicking "Install on internal storage", it just shows "Downloading Module, please wait."
Nothing will happen then.
Maybe there is a problem with wget? When running it from the console i get:
Error relocating /usr/lib/libuclient.so: usock_inet_timeout: symbol not found
Error relocating /lib/libubox.so: __ctype_b: symbol not found

**Comment by SecurityAddicted** [comment]
Unfortunately version 2.0.2 is still work in progress, it has a few issues. To fix this problem, try from the SSH console:
`rm -rf /bin/wget`
This should remove a wrong simlink and let you use wget from /usr/bin/.

**Comment by l0ndon** [comment]
Thank you, that was the problem! Now the modules can be installed.

**Comment by SecurityAddicted** [comment]
Fixed version uploaded. All the problems known so far should have been sorted. Try it and let me know.

**Comment by careyer** [comment]
Thank you very much! This issue has been fixed!
