### ISSUE TITLE
Does the second external antenna have to be ar9271 ?

### ISSUE THREAD

**Issue by ghost** [SecurityAddicted/pineapple-ar150#7]
I noticed that in your article,you said "I compiled it with support to all common USB WiFi adapters (I tested it with a TP-Link TL-WN722N)",so i want to know does the second antenna have any limits?
Do i have to use the adapter with chipset ar9271?

**Comment by SecurityAddicted** [comment]
Any Atheros card should work, and most Realteks like Alfa's 036.

**Comment by ghost** [comment]
Thanks a lot !!
