### ISSUE TITLE
Eth interface comes up with wrong IP (192.168.1.1 instead of 172.16.42.1)

### ISSUE THREAD

**Issue by careyer** [SecurityAddicted/pineapple-ar150#8]
I think this deserves a separate Issue. It was already discussed and confirmed in #5 but does not really belong there

@SecurityAddicted : I have spent some more days trying the latest image. Is there any possibility to fix the wrong IP address issue? Can you reconstruct that issue?
I have tried to rule out any external influences. i.e: I connect AP150 and my PC via a direct Ethernet cross-link cable (so no router/switch is involved). The PC does NOT run a DHCP server.

So here is what I do:
a.) configure static IP for PC ethernet: 192.168.1.2
b.) flash your firmware to the AL150 via its Fimrware Flash GUI at 192.168.1.1
c.) AL150 reboots after successfull firmware flash. Its ethnet interface comes up as 172.16.42.1
d.) reconfigure static IP for PC ethernet: 172.16.42.42
e.) connect WifiPinapple at 172.16.42.1:1471 and perform first time setup wizrd (works just fine)
f.) reboot WifiPinapple ... its ethernet interface will now come up as 192.168.1.1 instead of 172.16.42.1 as before on its first boot after flashing

After reconfiguring the PC back to a 192.168.1.x address one can still connect to the WiFi-Pinapple GUI. However most module and plugins expect the Gateway to be in the 172.16.42.x network.

Hope that helped!
Happy to hear from you!
Thomas

**Comment by SecurityAddicted** [comment]
Fixed version uploaded. All the problems known so far should have been sorted. Try it and let me know.

**Comment by careyer** [comment]
Thanks dude! That is great news... I will test this out as soon as I am back home!

**Comment by careyer** [comment]
Perfect! This issue has been fixed! Thank you very much for the effort!
